### ISSUE TITLE
makes admin slower

### ISSUE THREAD

**Issue by jayjay3108** [foxly-it/Mailcow-Darkmode#1] opened 2022-01-19 15:09 UTC
put the code in the correct file, made a docker-compose restart and now the admin is very slow. changed again to normal and admin is fast as usal

**Comment by foxly-it** [comment] 2022-01-19 15:32
Hello, for this customization it is not necessary to restart the containers. Can you tell me exactly what seems slower?
Since this customization only overwrites the css classes, I can't reproduce this.
Regards

**Comment by foxly-it** [comment] 2022-01-22 21:58
I cannot reproduce the behavior mentioned. I close the issue, if it happens again I would need some more information.

**Closed as completed by foxly-it** 2022-01-22 21:58 UTC
Labels: good first issue

**Comment by jayjay3108** [comment] 2022-01-23 20:29
Yes, you can close it. It was caused by an older version of the cow. Not it runs everything perfect. Thank you for your goodjob.

may an fr: a switch or botton to change from bright to dark and from dark to bright.

and may this would bringt it with a pr to cow standard :)

**Comment by foxly-it** [comment] 2022-01-24 07:43
> Yes, you can close it. It was caused by an older version of the cow. Not it runs everything perfect. Thank you for your goodjob.
> 
> may an fr: a switch or botton to change from bright to dark and from dark to bright.
> 
> and may this would bringt it with a pr to cow standard :)

Thank you for your reply, I had thought of something like that. Let's see how that would be realized.
